FROM oven/bun

WORKDIR /app

COPY package.json .
COPY bun.lockb .

# RUN chown -R $(whoami) $(pwd)

RUN bun install
RUN bun prisma:generate

COPY src src
COPY tsconfig.json .
COPY prisma ./prisma/

ENV NODE_ENV development
CMD ["bun", "--watch", "src/index.ts"]

EXPOSE 3000