FROM oven/bun

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install

COPY src src
COPY .env .env
COPY tsconfig.json .
COPY prisma prisma
RUN bun prisma:generate
RUN bun prisma:migrate
# RUN bun prisma:migrate

ENV NODE_ENV development
CMD ["bun", "--watch", "src/index.ts"]

EXPOSE 3000