FROM oven/bun

WORKDIR /app

COPY package.json .
COPY bun.lockb .

RUN bun install

COPY src src
COPY tsconfig.json .
COPY prisma prisma

ENV NODE_ENV development
CMD ["bun", "--watch", "src/index.ts"]

EXPOSE 3000